# Autogenerated using ProtoBuf.jl v1.2.3


module mpocircuit_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Mpo, MpoCircuit


struct Mpo
    nb_tensors::Int64
    nb_qubits::Int64
    bondims::Vector{Int64}
    max_bondim::Int64
    ocean::Int64
end
PB.default_values(::Type{Mpo}) = (;nb_tensors = zero(Int64), nb_qubits = zero(Int64), bondims = Vector{Int64}(), max_bondim = zero(Int64), ocean = zero(Int64))
PB.field_numbers(::Type{Mpo}) = (;nb_tensors = 1, nb_qubits = 2, bondims = 3, max_bondim = 4, ocean = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Mpo})
    nb_tensors = zero(Int64)
    nb_qubits = zero(Int64)
    bondims = PB.BufferedVector{Int64}()
    max_bondim = zero(Int64)
    ocean = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            nb_tensors = PB.decode(d, Int64)
        elseif field_number == 2
            nb_qubits = PB.decode(d, Int64)
        elseif field_number == 3
            PB.decode!(d, wire_type, bondims)
        elseif field_number == 4
            max_bondim = PB.decode(d, Int64)
        elseif field_number == 5
            ocean = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Mpo(nb_tensors, nb_qubits, bondims[], max_bondim, ocean)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Mpo)
    initpos = position(e.io)
    x.nb_tensors != zero(Int64) && PB.encode(e, 1, x.nb_tensors)
    x.nb_qubits != zero(Int64) && PB.encode(e, 2, x.nb_qubits)
    !isempty(x.bondims) && PB.encode(e, 3, x.bondims)
    x.max_bondim != zero(Int64) && PB.encode(e, 4, x.max_bondim)
    x.ocean != zero(Int64) && PB.encode(e, 5, x.ocean)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Mpo)
    encoded_size = 0
    x.nb_tensors != zero(Int64) && (encoded_size += PB._encoded_size(x.nb_tensors, 1))
    x.nb_qubits != zero(Int64) && (encoded_size += PB._encoded_size(x.nb_qubits, 2))
    !isempty(x.bondims) && (encoded_size += PB._encoded_size(x.bondims, 3))
    x.max_bondim != zero(Int64) && (encoded_size += PB._encoded_size(x.max_bondim, 4))
    x.ocean != zero(Int64) && (encoded_size += PB._encoded_size(x.ocean, 5))
    return encoded_size
end

struct MpoCircuit
    mpos::Vector{Mpo}
end
PB.default_values(::Type{MpoCircuit}) = (;mpos = Vector{Mpo}())
PB.field_numbers(::Type{MpoCircuit}) = (;mpos = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MpoCircuit})
    mpos = PB.BufferedVector{Mpo}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, mpos)
        else
            Base.skip(d, wire_type)
        end
    end
    return MpoCircuit(mpos[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MpoCircuit)
    initpos = position(e.io)
    !isempty(x.mpos) && PB.encode(e, 1, x.mpos)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MpoCircuit)
    encoded_size = 0
    !isempty(x.mpos) && (encoded_size += PB._encoded_size(x.mpos, 1))
    return encoded_size
end
end # module