# Autogenerated using ProtoBuf.jl v1.2.3


module mpssim_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export FlatTensor, ClassicalState, ComplexState, MpoNorm, MPS, MPO, MPSState, MpoCircuit


struct FlatTensor
    dims::Vector{Int64}
    is_complex::Bool
    data::Vector{Float64}
end
PB.default_values(::Type{FlatTensor}) = (;dims = Vector{Int64}(), is_complex = false, data = Vector{Float64}())
PB.field_numbers(::Type{FlatTensor}) = (;dims = 1, is_complex = 2, data = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FlatTensor})
    dims = PB.BufferedVector{Int64}()
    is_complex = false
    data = PB.BufferedVector{Float64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, dims)
        elseif field_number == 2
            is_complex = PB.decode(d, Bool)
        elseif field_number == 3
            PB.decode!(d, wire_type, data)
        else
            Base.skip(d, wire_type)
        end
    end
    return FlatTensor(dims[], is_complex, data[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FlatTensor)
    initpos = position(e.io)
    !isempty(x.dims) && PB.encode(e, 1, x.dims)
    x.is_complex != false && PB.encode(e, 2, x.is_complex)
    !isempty(x.data) && PB.encode(e, 3, x.data)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FlatTensor)
    encoded_size = 0
    !isempty(x.dims) && (encoded_size += PB._encoded_size(x.dims, 1))
    x.is_complex != false && (encoded_size += PB._encoded_size(x.is_complex, 2))
    !isempty(x.data) && (encoded_size += PB._encoded_size(x.data, 3))
    return encoded_size
end

struct ClassicalState
    bits::Vector{Bool}
end
PB.default_values(::Type{ClassicalState}) = (;bits = Vector{Bool}())
PB.field_numbers(::Type{ClassicalState}) = (;bits = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ClassicalState})
    bits = PB.BufferedVector{Bool}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, bits)
        else
            Base.skip(d, wire_type)
        end
    end
    return ClassicalState(bits[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ClassicalState)
    initpos = position(e.io)
    !isempty(x.bits) && PB.encode(e, 1, x.bits)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ClassicalState)
    encoded_size = 0
    !isempty(x.bits) && (encoded_size += PB._encoded_size(x.bits, 1))
    return encoded_size
end

struct ComplexState
    values::Vector{Float64}
end
PB.default_values(::Type{ComplexState}) = (;values = Vector{Float64}())
PB.field_numbers(::Type{ComplexState}) = (;values = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ComplexState})
    values = PB.BufferedVector{Float64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, values)
        else
            Base.skip(d, wire_type)
        end
    end
    return ComplexState(values[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ComplexState)
    initpos = position(e.io)
    !isempty(x.values) && PB.encode(e, 1, x.values)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ComplexState)
    encoded_size = 0
    !isempty(x.values) && (encoded_size += PB._encoded_size(x.values, 1))
    return encoded_size
end

@enumx MpoNorm OPERATOR=0 TRACE=1

struct MPS
    num_tensors::Int64
    num_qubits::Int64
    physical_dims::Vector{Int64}
    max_bond_dim::Int64
    bond_dims::Vector{Int64}
    tensors::Vector{FlatTensor}
    ortho_center::Int64
end
PB.default_values(::Type{MPS}) = (;num_tensors = zero(Int64), num_qubits = zero(Int64), physical_dims = Vector{Int64}(), max_bond_dim = zero(Int64), bond_dims = Vector{Int64}(), tensors = Vector{FlatTensor}(), ortho_center = zero(Int64))
PB.field_numbers(::Type{MPS}) = (;num_tensors = 1, num_qubits = 2, physical_dims = 3, max_bond_dim = 4, bond_dims = 5, tensors = 6, ortho_center = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MPS})
    num_tensors = zero(Int64)
    num_qubits = zero(Int64)
    physical_dims = PB.BufferedVector{Int64}()
    max_bond_dim = zero(Int64)
    bond_dims = PB.BufferedVector{Int64}()
    tensors = PB.BufferedVector{FlatTensor}()
    ortho_center = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            num_tensors = PB.decode(d, Int64)
        elseif field_number == 2
            num_qubits = PB.decode(d, Int64)
        elseif field_number == 3
            PB.decode!(d, wire_type, physical_dims)
        elseif field_number == 4
            max_bond_dim = PB.decode(d, Int64)
        elseif field_number == 5
            PB.decode!(d, wire_type, bond_dims)
        elseif field_number == 6
            PB.decode!(d, tensors)
        elseif field_number == 7
            ortho_center = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return MPS(num_tensors, num_qubits, physical_dims[], max_bond_dim, bond_dims[], tensors[], ortho_center)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MPS)
    initpos = position(e.io)
    x.num_tensors != zero(Int64) && PB.encode(e, 1, x.num_tensors)
    x.num_qubits != zero(Int64) && PB.encode(e, 2, x.num_qubits)
    !isempty(x.physical_dims) && PB.encode(e, 3, x.physical_dims)
    x.max_bond_dim != zero(Int64) && PB.encode(e, 4, x.max_bond_dim)
    !isempty(x.bond_dims) && PB.encode(e, 5, x.bond_dims)
    !isempty(x.tensors) && PB.encode(e, 6, x.tensors)
    x.ortho_center != zero(Int64) && PB.encode(e, 7, x.ortho_center)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MPS)
    encoded_size = 0
    x.num_tensors != zero(Int64) && (encoded_size += PB._encoded_size(x.num_tensors, 1))
    x.num_qubits != zero(Int64) && (encoded_size += PB._encoded_size(x.num_qubits, 2))
    !isempty(x.physical_dims) && (encoded_size += PB._encoded_size(x.physical_dims, 3))
    x.max_bond_dim != zero(Int64) && (encoded_size += PB._encoded_size(x.max_bond_dim, 4))
    !isempty(x.bond_dims) && (encoded_size += PB._encoded_size(x.bond_dims, 5))
    !isempty(x.tensors) && (encoded_size += PB._encoded_size(x.tensors, 6))
    x.ortho_center != zero(Int64) && (encoded_size += PB._encoded_size(x.ortho_center, 7))
    return encoded_size
end

struct MPO
    num_tensors::Int64
    num_qubits::Int64
    physical_dims::Vector{Int64}
    max_bond_dim::Int64
    bond_dims::Vector{Int64}
    tensors::Vector{FlatTensor}
    ortho_center::Int64
    norm::MpoNorm.T
end
PB.default_values(::Type{MPO}) = (;num_tensors = zero(Int64), num_qubits = zero(Int64), physical_dims = Vector{Int64}(), max_bond_dim = zero(Int64), bond_dims = Vector{Int64}(), tensors = Vector{FlatTensor}(), ortho_center = zero(Int64), norm = MpoNorm.OPERATOR)
PB.field_numbers(::Type{MPO}) = (;num_tensors = 1, num_qubits = 2, physical_dims = 3, max_bond_dim = 4, bond_dims = 5, tensors = 6, ortho_center = 7, norm = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MPO})
    num_tensors = zero(Int64)
    num_qubits = zero(Int64)
    physical_dims = PB.BufferedVector{Int64}()
    max_bond_dim = zero(Int64)
    bond_dims = PB.BufferedVector{Int64}()
    tensors = PB.BufferedVector{FlatTensor}()
    ortho_center = zero(Int64)
    norm = MpoNorm.OPERATOR
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            num_tensors = PB.decode(d, Int64)
        elseif field_number == 2
            num_qubits = PB.decode(d, Int64)
        elseif field_number == 3
            PB.decode!(d, wire_type, physical_dims)
        elseif field_number == 4
            max_bond_dim = PB.decode(d, Int64)
        elseif field_number == 5
            PB.decode!(d, wire_type, bond_dims)
        elseif field_number == 6
            PB.decode!(d, tensors)
        elseif field_number == 7
            ortho_center = PB.decode(d, Int64)
        elseif field_number == 8
            norm = PB.decode(d, MpoNorm.T)
        else
            Base.skip(d, wire_type)
        end
    end
    return MPO(num_tensors, num_qubits, physical_dims[], max_bond_dim, bond_dims[], tensors[], ortho_center, norm)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MPO)
    initpos = position(e.io)
    x.num_tensors != zero(Int64) && PB.encode(e, 1, x.num_tensors)
    x.num_qubits != zero(Int64) && PB.encode(e, 2, x.num_qubits)
    !isempty(x.physical_dims) && PB.encode(e, 3, x.physical_dims)
    x.max_bond_dim != zero(Int64) && PB.encode(e, 4, x.max_bond_dim)
    !isempty(x.bond_dims) && PB.encode(e, 5, x.bond_dims)
    !isempty(x.tensors) && PB.encode(e, 6, x.tensors)
    x.ortho_center != zero(Int64) && PB.encode(e, 7, x.ortho_center)
    x.norm != MpoNorm.OPERATOR && PB.encode(e, 8, x.norm)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MPO)
    encoded_size = 0
    x.num_tensors != zero(Int64) && (encoded_size += PB._encoded_size(x.num_tensors, 1))
    x.num_qubits != zero(Int64) && (encoded_size += PB._encoded_size(x.num_qubits, 2))
    !isempty(x.physical_dims) && (encoded_size += PB._encoded_size(x.physical_dims, 3))
    x.max_bond_dim != zero(Int64) && (encoded_size += PB._encoded_size(x.max_bond_dim, 4))
    !isempty(x.bond_dims) && (encoded_size += PB._encoded_size(x.bond_dims, 5))
    !isempty(x.tensors) && (encoded_size += PB._encoded_size(x.tensors, 6))
    x.ortho_center != zero(Int64) && (encoded_size += PB._encoded_size(x.ortho_center, 7))
    x.norm != MpoNorm.OPERATOR && (encoded_size += PB._encoded_size(x.norm, 8))
    return encoded_size
end

struct MPSState
    q::Union{Nothing,MPS}
    c::Union{Nothing,ClassicalState}
    z::Union{Nothing,ComplexState}
end
PB.default_values(::Type{MPSState}) = (;q = nothing, c = nothing, z = nothing)
PB.field_numbers(::Type{MPSState}) = (;q = 1, c = 2, z = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MPSState})
    q = Ref{Union{Nothing,MPS}}(nothing)
    c = Ref{Union{Nothing,ClassicalState}}(nothing)
    z = Ref{Union{Nothing,ComplexState}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, q)
        elseif field_number == 2
            PB.decode!(d, c)
        elseif field_number == 3
            PB.decode!(d, z)
        else
            Base.skip(d, wire_type)
        end
    end
    return MPSState(q[], c[], z[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MPSState)
    initpos = position(e.io)
    !isnothing(x.q) && PB.encode(e, 1, x.q)
    !isnothing(x.c) && PB.encode(e, 2, x.c)
    !isnothing(x.z) && PB.encode(e, 3, x.z)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MPSState)
    encoded_size = 0
    !isnothing(x.q) && (encoded_size += PB._encoded_size(x.q, 1))
    !isnothing(x.c) && (encoded_size += PB._encoded_size(x.c, 2))
    !isnothing(x.z) && (encoded_size += PB._encoded_size(x.z, 3))
    return encoded_size
end

struct MpoCircuit
    mpos::Vector{MPO}
end
PB.default_values(::Type{MpoCircuit}) = (;mpos = Vector{MPO}())
PB.field_numbers(::Type{MpoCircuit}) = (;mpos = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MpoCircuit})
    mpos = PB.BufferedVector{MPO}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, mpos)
        else
            Base.skip(d, wire_type)
        end
    end
    return MpoCircuit(mpos[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MpoCircuit)
    initpos = position(e.io)
    !isempty(x.mpos) && PB.encode(e, 1, x.mpos)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MpoCircuit)
    encoded_size = 0
    !isempty(x.mpos) && (encoded_size += PB._encoded_size(x.mpos, 1))
    return encoded_size
end
end # module