# Autogenerated using ProtoBuf.jl v1.2.3


module qcsresults_pb


import ..utils_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export AmplitudeEntry, QCSResults


struct AmplitudeEntry
    key::Union{Nothing,utils_pb.BitVector}
    val::Union{Nothing,utils_pb.ComplexDouble}
end
PB.default_values(::Type{AmplitudeEntry}) = (;key = nothing, val = nothing)
PB.field_numbers(::Type{AmplitudeEntry}) = (;key = 1, val = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AmplitudeEntry})
    key = Ref{Union{Nothing,utils_pb.BitVector}}(nothing)
    val = Ref{Union{Nothing,utils_pb.ComplexDouble}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, key)
        elseif field_number == 2
            PB.decode!(d, val)
        else
            Base.skip(d, wire_type)
        end
    end
    return AmplitudeEntry(key[], val[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AmplitudeEntry)
    initpos = position(e.io)
    !isnothing(x.key) && PB.encode(e, 1, x.key)
    !isnothing(x.val) && PB.encode(e, 2, x.val)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AmplitudeEntry)
    encoded_size = 0
    !isnothing(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    !isnothing(x.val) && (encoded_size += PB._encoded_size(x.val, 2))
    return encoded_size
end

struct QCSResults
    simulator::String
    version::String
    fidelities::Vector{Float64}
    avggateerrors::Vector{Float64}
    cstates::Vector{utils_pb.BitVector}
    zstates::Vector{utils_pb.ComplexVector}
    amplitudes::Vector{AmplitudeEntry}
    timings::Dict{String,Float64}
end
PB.default_values(::Type{QCSResults}) = (;simulator = "", version = "", fidelities = Vector{Float64}(), avggateerrors = Vector{Float64}(), cstates = Vector{utils_pb.BitVector}(), zstates = Vector{utils_pb.ComplexVector}(), amplitudes = Vector{AmplitudeEntry}(), timings = Dict{String,Float64}())
PB.field_numbers(::Type{QCSResults}) = (;simulator = 1, version = 2, fidelities = 3, avggateerrors = 4, cstates = 5, zstates = 6, amplitudes = 7, timings = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:QCSResults})
    simulator = ""
    version = ""
    fidelities = PB.BufferedVector{Float64}()
    avggateerrors = PB.BufferedVector{Float64}()
    cstates = PB.BufferedVector{utils_pb.BitVector}()
    zstates = PB.BufferedVector{utils_pb.ComplexVector}()
    amplitudes = PB.BufferedVector{AmplitudeEntry}()
    timings = Dict{String,Float64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            simulator = PB.decode(d, String)
        elseif field_number == 2
            version = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, wire_type, fidelities)
        elseif field_number == 4
            PB.decode!(d, wire_type, avggateerrors)
        elseif field_number == 5
            PB.decode!(d, cstates)
        elseif field_number == 6
            PB.decode!(d, zstates)
        elseif field_number == 7
            PB.decode!(d, amplitudes)
        elseif field_number == 8
            PB.decode!(d, timings)
        else
            Base.skip(d, wire_type)
        end
    end
    return QCSResults(simulator, version, fidelities[], avggateerrors[], cstates[], zstates[], amplitudes[], timings)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::QCSResults)
    initpos = position(e.io)
    !isempty(x.simulator) && PB.encode(e, 1, x.simulator)
    !isempty(x.version) && PB.encode(e, 2, x.version)
    !isempty(x.fidelities) && PB.encode(e, 3, x.fidelities)
    !isempty(x.avggateerrors) && PB.encode(e, 4, x.avggateerrors)
    !isempty(x.cstates) && PB.encode(e, 5, x.cstates)
    !isempty(x.zstates) && PB.encode(e, 6, x.zstates)
    !isempty(x.amplitudes) && PB.encode(e, 7, x.amplitudes)
    !isempty(x.timings) && PB.encode(e, 8, x.timings)
    return position(e.io) - initpos
end
function PB._encoded_size(x::QCSResults)
    encoded_size = 0
    !isempty(x.simulator) && (encoded_size += PB._encoded_size(x.simulator, 1))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 2))
    !isempty(x.fidelities) && (encoded_size += PB._encoded_size(x.fidelities, 3))
    !isempty(x.avggateerrors) && (encoded_size += PB._encoded_size(x.avggateerrors, 4))
    !isempty(x.cstates) && (encoded_size += PB._encoded_size(x.cstates, 5))
    !isempty(x.zstates) && (encoded_size += PB._encoded_size(x.zstates, 6))
    !isempty(x.amplitudes) && (encoded_size += PB._encoded_size(x.amplitudes, 7))
    !isempty(x.timings) && (encoded_size += PB._encoded_size(x.timings, 8))
    return encoded_size
end
end # module