# Autogenerated using ProtoBuf.jl v1.2.3


module statevecsim_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export StateVectorLight


struct StateVectorLight
    sv_size::Int64
end
PB.default_values(::Type{StateVectorLight}) = (;sv_size = zero(Int64))
PB.field_numbers(::Type{StateVectorLight}) = (;sv_size = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StateVectorLight})
    sv_size = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 2
            sv_size = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return StateVectorLight(sv_size)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StateVectorLight)
    initpos = position(e.io)
    x.sv_size != zero(Int64) && PB.encode(e, 2, x.sv_size)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StateVectorLight)
    encoded_size = 0
    x.sv_size != zero(Int64) && (encoded_size += PB._encoded_size(x.sv_size, 2))
    return encoded_size
end
end # module