# Autogenerated using ProtoBuf.jl v1.2.3


module tensorweaver_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export TensorWeaverLight


struct TensorWeaverLight end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TensorWeaverLight})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return TensorWeaverLight()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TensorWeaverLight)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TensorWeaverLight)
    encoded_size = 0
    return encoded_size
end
end # module