# Autogenerated using ProtoBuf.jl v1.2.3


module tracefile_pb


import ..mpocircuit_pb

import ..circuit_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Tracefile


struct Tracefile
    mimiq_circuit::Union{Nothing,circuit_pb.Circuit}
    mpo_circuit::Union{Nothing,mpocircuit_pb.MpoCircuit}
    inst_to_mpo::Dict{Int64,Int64}
    mpo_to_inst::Dict{Int64,Int64}
end
PB.default_values(::Type{Tracefile}) = (;mimiq_circuit = nothing, mpo_circuit = nothing, inst_to_mpo = Dict{Int64,Int64}(), mpo_to_inst = Dict{Int64,Int64}())
PB.field_numbers(::Type{Tracefile}) = (;mimiq_circuit = 1, mpo_circuit = 2, inst_to_mpo = 3, mpo_to_inst = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Tracefile})
    mimiq_circuit = Ref{Union{Nothing,circuit_pb.Circuit}}(nothing)
    mpo_circuit = Ref{Union{Nothing,mpocircuit_pb.MpoCircuit}}(nothing)
    inst_to_mpo = Dict{Int64,Int64}()
    mpo_to_inst = Dict{Int64,Int64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, mimiq_circuit)
        elseif field_number == 2
            PB.decode!(d, mpo_circuit)
        elseif field_number == 3
            PB.decode!(d, inst_to_mpo)
        elseif field_number == 4
            PB.decode!(d, mpo_to_inst)
        else
            Base.skip(d, wire_type)
        end
    end
    return Tracefile(mimiq_circuit[], mpo_circuit[], inst_to_mpo, mpo_to_inst)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Tracefile)
    initpos = position(e.io)
    !isnothing(x.mimiq_circuit) && PB.encode(e, 1, x.mimiq_circuit)
    !isnothing(x.mpo_circuit) && PB.encode(e, 2, x.mpo_circuit)
    !isempty(x.inst_to_mpo) && PB.encode(e, 3, x.inst_to_mpo)
    !isempty(x.mpo_to_inst) && PB.encode(e, 4, x.mpo_to_inst)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Tracefile)
    encoded_size = 0
    !isnothing(x.mimiq_circuit) && (encoded_size += PB._encoded_size(x.mimiq_circuit, 1))
    !isnothing(x.mpo_circuit) && (encoded_size += PB._encoded_size(x.mpo_circuit, 2))
    !isempty(x.inst_to_mpo) && (encoded_size += PB._encoded_size(x.inst_to_mpo, 3))
    !isempty(x.mpo_to_inst) && (encoded_size += PB._encoded_size(x.mpo_to_inst, 4))
    return encoded_size
end
end # module