# Autogenerated using ProtoBuf.jl v1.2.3


module tracefile_pb


import ..utils_pb

import ..statevecsim_pb

import ..mpssim_pb

import ..tensorweaver_pb

import ..circuit_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Pair, Backend, StateInfo, Tracefile


struct Pair
    first::Int64
    second::Int64
end
PB.default_values(::Type{Pair}) = (;first = zero(Int64), second = zero(Int64))
PB.field_numbers(::Type{Pair}) = (;first = 1, second = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Pair})
    first = zero(Int64)
    second = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            first = PB.decode(d, Int64)
        elseif field_number == 2
            second = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Pair(first, second)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Pair)
    initpos = position(e.io)
    x.first != zero(Int64) && PB.encode(e, 1, x.first)
    x.second != zero(Int64) && PB.encode(e, 2, x.second)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Pair)
    encoded_size = 0
    x.first != zero(Int64) && (encoded_size += PB._encoded_size(x.first, 1))
    x.second != zero(Int64) && (encoded_size += PB._encoded_size(x.second, 2))
    return encoded_size
end

@enumx Backend StateVector=0 MatrixProductState=1 TensorWeaver=2 Undefined=3

struct StateInfo
    num_qubits::Int64
    state::Union{Nothing,OneOf{<:Union{statevecsim_pb.StateVectorLight,mpssim_pb.MPSLight,tensorweaver_pb.TensorWeaverLight}}}
    c::Union{Nothing,utils_pb.BitVector}
    z::Union{Nothing,utils_pb.ComplexVector}
end
PB.oneof_field_types(::Type{StateInfo}) = (;
    state = (;sv=statevecsim_pb.StateVectorLight, mps=mpssim_pb.MPSLight, tensorweaver=tensorweaver_pb.TensorWeaverLight),
)
PB.default_values(::Type{StateInfo}) = (;num_qubits = zero(Int64), sv = nothing, mps = nothing, tensorweaver = nothing, c = nothing, z = nothing)
PB.field_numbers(::Type{StateInfo}) = (;num_qubits = 1, sv = 2, mps = 3, tensorweaver = 4, c = 5, z = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StateInfo})
    num_qubits = zero(Int64)
    state = nothing
    c = Ref{Union{Nothing,utils_pb.BitVector}}(nothing)
    z = Ref{Union{Nothing,utils_pb.ComplexVector}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            num_qubits = PB.decode(d, Int64)
        elseif field_number == 2
            state = OneOf(:sv, PB.decode(d, Ref{statevecsim_pb.StateVectorLight}))
        elseif field_number == 3
            state = OneOf(:mps, PB.decode(d, Ref{mpssim_pb.MPSLight}))
        elseif field_number == 4
            state = OneOf(:tensorweaver, PB.decode(d, Ref{tensorweaver_pb.TensorWeaverLight}))
        elseif field_number == 5
            PB.decode!(d, c)
        elseif field_number == 6
            PB.decode!(d, z)
        else
            Base.skip(d, wire_type)
        end
    end
    return StateInfo(num_qubits, state, c[], z[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StateInfo)
    initpos = position(e.io)
    x.num_qubits != zero(Int64) && PB.encode(e, 1, x.num_qubits)
    if isnothing(x.state);
    elseif x.state.name === :sv
        PB.encode(e, 2, x.state[]::statevecsim_pb.StateVectorLight)
    elseif x.state.name === :mps
        PB.encode(e, 3, x.state[]::mpssim_pb.MPSLight)
    elseif x.state.name === :tensorweaver
        PB.encode(e, 4, x.state[]::tensorweaver_pb.TensorWeaverLight)
    end
    !isnothing(x.c) && PB.encode(e, 5, x.c)
    !isnothing(x.z) && PB.encode(e, 6, x.z)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StateInfo)
    encoded_size = 0
    x.num_qubits != zero(Int64) && (encoded_size += PB._encoded_size(x.num_qubits, 1))
    if isnothing(x.state);
    elseif x.state.name === :sv
        encoded_size += PB._encoded_size(x.state[]::statevecsim_pb.StateVectorLight, 2)
    elseif x.state.name === :mps
        encoded_size += PB._encoded_size(x.state[]::mpssim_pb.MPSLight, 3)
    elseif x.state.name === :tensorweaver
        encoded_size += PB._encoded_size(x.state[]::tensorweaver_pb.TensorWeaverLight, 4)
    end
    !isnothing(x.c) && (encoded_size += PB._encoded_size(x.c, 5))
    !isnothing(x.z) && (encoded_size += PB._encoded_size(x.z, 6))
    return encoded_size
end

struct Tracefile
    backend::Backend.T
    original_circuit::Union{Nothing,circuit_pb.Circuit}
    optimized_circuit::Union{Nothing,circuit_pb.Circuit}
    state_evolution::Vector{StateInfo}
end
PB.default_values(::Type{Tracefile}) = (;backend = Backend.StateVector, original_circuit = nothing, optimized_circuit = nothing, state_evolution = Vector{StateInfo}())
PB.field_numbers(::Type{Tracefile}) = (;backend = 1, original_circuit = 2, optimized_circuit = 3, state_evolution = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Tracefile})
    backend = Backend.StateVector
    original_circuit = Ref{Union{Nothing,circuit_pb.Circuit}}(nothing)
    optimized_circuit = Ref{Union{Nothing,circuit_pb.Circuit}}(nothing)
    state_evolution = PB.BufferedVector{StateInfo}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            backend = PB.decode(d, Backend.T)
        elseif field_number == 2
            PB.decode!(d, original_circuit)
        elseif field_number == 3
            PB.decode!(d, optimized_circuit)
        elseif field_number == 4
            PB.decode!(d, state_evolution)
        else
            Base.skip(d, wire_type)
        end
    end
    return Tracefile(backend, original_circuit[], optimized_circuit[], state_evolution[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Tracefile)
    initpos = position(e.io)
    x.backend != Backend.StateVector && PB.encode(e, 1, x.backend)
    !isnothing(x.original_circuit) && PB.encode(e, 2, x.original_circuit)
    !isnothing(x.optimized_circuit) && PB.encode(e, 3, x.optimized_circuit)
    !isempty(x.state_evolution) && PB.encode(e, 4, x.state_evolution)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Tracefile)
    encoded_size = 0
    x.backend != Backend.StateVector && (encoded_size += PB._encoded_size(x.backend, 1))
    !isnothing(x.original_circuit) && (encoded_size += PB._encoded_size(x.original_circuit, 2))
    !isnothing(x.optimized_circuit) && (encoded_size += PB._encoded_size(x.optimized_circuit, 3))
    !isempty(x.state_evolution) && (encoded_size += PB._encoded_size(x.state_evolution, 4))
    return encoded_size
end
end # module