# Autogenerated using ProtoBuf.jl v1.2.3


module tracefile_pb


import ..mpssim_pb

import ..circuit_pb
import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Pair, Tracefile


struct Pair
    first::Int64
    second::Int64
end
PB.default_values(::Type{Pair}) = (;first = zero(Int64), second = zero(Int64))
PB.field_numbers(::Type{Pair}) = (;first = 1, second = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Pair})
    first = zero(Int64)
    second = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            first = PB.decode(d, Int64)
        elseif field_number == 2
            second = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return Pair(first, second)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Pair)
    initpos = position(e.io)
    x.first != zero(Int64) && PB.encode(e, 1, x.first)
    x.second != zero(Int64) && PB.encode(e, 2, x.second)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Pair)
    encoded_size = 0
    x.first != zero(Int64) && (encoded_size += PB._encoded_size(x.first, 1))
    x.second != zero(Int64) && (encoded_size += PB._encoded_size(x.second, 2))
    return encoded_size
end

struct Tracefile
    mimiq_circuit::Union{Nothing,circuit_pb.Circuit}
    converted_circuit::Union{Nothing,mpssim_pb.MpoCircuit}
    inst_to_mpo::Vector{Pair}
    state_evolution::Vector{mpssim_pb.MPSState}
end
PB.default_values(::Type{Tracefile}) = (;mimiq_circuit = nothing, converted_circuit = nothing, inst_to_mpo = Vector{Pair}(), state_evolution = Vector{mpssim_pb.MPSState}())
PB.field_numbers(::Type{Tracefile}) = (;mimiq_circuit = 1, converted_circuit = 2, inst_to_mpo = 3, state_evolution = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Tracefile})
    mimiq_circuit = Ref{Union{Nothing,circuit_pb.Circuit}}(nothing)
    converted_circuit = Ref{Union{Nothing,mpssim_pb.MpoCircuit}}(nothing)
    inst_to_mpo = PB.BufferedVector{Pair}()
    state_evolution = PB.BufferedVector{mpssim_pb.MPSState}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, mimiq_circuit)
        elseif field_number == 2
            PB.decode!(d, converted_circuit)
        elseif field_number == 3
            PB.decode!(d, inst_to_mpo)
        elseif field_number == 4
            PB.decode!(d, state_evolution)
        else
            Base.skip(d, wire_type)
        end
    end
    return Tracefile(mimiq_circuit[], converted_circuit[], inst_to_mpo[], state_evolution[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Tracefile)
    initpos = position(e.io)
    !isnothing(x.mimiq_circuit) && PB.encode(e, 1, x.mimiq_circuit)
    !isnothing(x.converted_circuit) && PB.encode(e, 2, x.converted_circuit)
    !isempty(x.inst_to_mpo) && PB.encode(e, 3, x.inst_to_mpo)
    !isempty(x.state_evolution) && PB.encode(e, 4, x.state_evolution)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Tracefile)
    encoded_size = 0
    !isnothing(x.mimiq_circuit) && (encoded_size += PB._encoded_size(x.mimiq_circuit, 1))
    !isnothing(x.converted_circuit) && (encoded_size += PB._encoded_size(x.converted_circuit, 2))
    !isempty(x.inst_to_mpo) && (encoded_size += PB._encoded_size(x.inst_to_mpo, 3))
    !isempty(x.state_evolution) && (encoded_size += PB._encoded_size(x.state_evolution, 4))
    return encoded_size
end
end # module