# Autogenerated using ProtoBuf.jl v1.2.3


module utils_pb

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ComplexDouble, BitVector, ComplexVector


struct ComplexDouble
    real::Float64
    imag::Float64
end
PB.default_values(::Type{ComplexDouble}) = (;real = zero(Float64), imag = zero(Float64))
PB.field_numbers(::Type{ComplexDouble}) = (;real = 1, imag = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ComplexDouble})
    real = zero(Float64)
    imag = zero(Float64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            real = PB.decode(d, Float64)
        elseif field_number == 2
            imag = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return ComplexDouble(real, imag)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ComplexDouble)
    initpos = position(e.io)
    x.real !== zero(Float64) && PB.encode(e, 1, x.real)
    x.imag !== zero(Float64) && PB.encode(e, 2, x.imag)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ComplexDouble)
    encoded_size = 0
    x.real !== zero(Float64) && (encoded_size += PB._encoded_size(x.real, 1))
    x.imag !== zero(Float64) && (encoded_size += PB._encoded_size(x.imag, 2))
    return encoded_size
end

struct BitVector
    len::Int64
    data::Vector{UInt8}
end
PB.default_values(::Type{BitVector}) = (;len = zero(Int64), data = UInt8[])
PB.field_numbers(::Type{BitVector}) = (;len = 1, data = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:BitVector})
    len = zero(Int64)
    data = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            len = PB.decode(d, Int64)
        elseif field_number == 2
            data = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return BitVector(len, data)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::BitVector)
    initpos = position(e.io)
    x.len != zero(Int64) && PB.encode(e, 1, x.len)
    !isempty(x.data) && PB.encode(e, 2, x.data)
    return position(e.io) - initpos
end
function PB._encoded_size(x::BitVector)
    encoded_size = 0
    x.len != zero(Int64) && (encoded_size += PB._encoded_size(x.len, 1))
    !isempty(x.data) && (encoded_size += PB._encoded_size(x.data, 2))
    return encoded_size
end

struct ComplexVector
    data::Vector{ComplexDouble}
end
PB.default_values(::Type{ComplexVector}) = (;data = Vector{ComplexDouble}())
PB.field_numbers(::Type{ComplexVector}) = (;data = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ComplexVector})
    data = PB.BufferedVector{ComplexDouble}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, data)
        else
            Base.skip(d, wire_type)
        end
    end
    return ComplexVector(data[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ComplexVector)
    initpos = position(e.io)
    !isempty(x.data) && PB.encode(e, 1, x.data)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ComplexVector)
    encoded_size = 0
    !isempty(x.data) && (encoded_size += PB._encoded_size(x.data, 1))
    return encoded_size
end
end # module