name = "ProtoParser"
uuid = "eaa421d0-1ae9-4acc-adc3-5fbe310b118d"
version = "0.1.0"
authors = ["Maxime-pixel <maxime.outteryck@qperfect.io>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MimiqCircuitsBase = "3a95eabf-73f4-453e-aae8-8a11a27ac032"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
DataStructures = "^0.19.3"
MimiqCircuitsBase = "^0.20.3"
ProtoBuf = "^1.2.0"
